version: '3'
services:
  backend:
    image: thuanpham00/qrtable-server:v0
    ports:
      - "4500:4000"
    volumes:
      - D:\VS_CODE\Project\Project-NodeJS-Other\QRTable-Restful-API\uploads:/app/uploads
    env_file:
      - .env